### PR TITLE
Maintenance: Rework layout of progress pie and recording dot

### PR DESCRIPTION
**Pull request by wutschel**
## Description

This PR removes further magic numbers, slightly changes the layout itself and reduces code duplication by introducing a helper method as suggested in earlier reviews. It needs to be updated once #974 is merged.

## Summary for release notes

Maintenance: Rework layout of progress pie and recording dot

### CODE REVIEW

**Comment by wutschel** [comment]
Let me now rebase this one.

**Comment by wutschel** [comment]
> should I wait with merging #974?

No, you can move ahead.

**Comment by wutschel** [comment]
Ok, there is still something (slightly but visibly) off with the vertical center of the recording icon. But this PR does not change the layout, this is already present in the code on master. Let's move ahead with reviewing.

**Review by kambala-decapitator — APPROVED** [review]
> Ok, there is still something (slightly but visibly) off with the vertical center of the recording icon

do you want to fix it in this PR or let's merge?

**Comment by wutschel** [comment]
I will have it in 1 hour.

**Comment by wutschel** [comment]
Added (and squashed) a small fix which places the center of the recording icon correctly above the progress pie.

**Pull request merged**
