### PR TITLE
Translations update from Kodi Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Kodi Weblate](https://kodi.weblate.cloud) for [Kodi remotes/Official iOS Remote (main)](https://kodi.weblate.cloud/projects/kodi-remotes/official-ios-remote-main/).

It also includes following components:

* [Kodi remotes/Official iOS Remote (settings)](https://kodi.weblate.cloud/projects/kodi-remotes/official-ios-remote-settings/)

* [Kodi remotes/Official iOS Remote (InfoPlist)](https://kodi.weblate.cloud/projects/kodi-remotes/official-ios-remote-infoplist/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by wutschel** [comment]
@ksooo, @gade01, in https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/619 it was discussed how a common and unified naming for "Wake On LAN" / Wake-On-LAN could be reached. Finally I decided to go for the signal's name with dashed (= Wake-On-LAN) for all places and languages. What is speaking against keeping it like this? Independent of this we should keep inconsistency as we have two places in the UI (App settings and main).

**Comment by gade01** [comment]
I think it makes sense and is a good decision to use `Wake-On-LAN`.

**Review by gade01 — APPROVED** [review]

**Review by gade01 — APPROVED** [review]

**Comment by wutschel** [comment]
@ksooo, can you help finding a solution for this?

**Comment by kambala-decapitator** [comment]
this is not ready for merge yet iiuc?

**Comment by wutschel** [comment]
> this is not ready for merge yet iiuc?

No, not yet. But I am in touch with @ksooo over Weblate. I think we'll sort this out soon.

**Comment by kambala-decapitator** [comment]
this is the only PR left before submitting the hotfix

**Comment by wutschel** [comment]
> this is the only PR left before submitting the hotfix

Imho we do not need to wait for this. The changes are not an urgent required fix and can come later.

On the hot fix: I would prefer to provide a TF build for a few days now and submit for release on weekend -- if nothing else is popping up.

**Comment by kambala-decapitator** [comment]
I agree, let's do like that

**Comment by wutschel** [comment]
Oh, now we misunderstood each other. I would have skipped this PR and go for a release without it. Now we have inconsistencies in German. Not a big deal though.

**Comment by kambala-decapitator** [comment]
I'm sorry!

I guess it's not safe to revert it now...

**Comment by wutschel** [comment]
No, keep it, it is just not optimal, but not hurting functionally in any way. In worst case I can still submit a rollback from here, or I ask @gade01 to help rolling back the one WOL translation for consistency until there is an agreement with @ksooo.

**Comment by gade01** [comment]
@kambala-decapitator @wutschel 
Yeah, please don't revert this PR as it also includes other languages.

@ksooo @wutschel As to the correct phrase in German the two of you should decide this.
@ksooo is the maintainer of the German language at Weblate, so please don't include me in this.

**Comment by wutschel** [comment]
Difficult to reach @ksooo. No response since a week now.

**Comment by kambala-decapitator** [comment]
> Difficult to reach @ksooo. No response since a week now.

we still have more than a week, maybe he's on holiday or busy IRL

**Pull request merged**
