### PR TITLE
AppInfo Dark Mode

### PR DESCRIPTION
**Pull request by wutschel**
## Description

Fixes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/328.

Correct text and background colors to follow Dark / Light Mode. Update the app icon, but keep the mascot.

Screenshots:
https://abload.de/img/simulatorscreenshot-it6ktr.png (Light Mode)
https://abload.de/img/simulatorscreenshot-ihfj5i.png (Dark Mode)

## Summary for release notes

Bugfix: Fix the Dark Mode for AppInfo
Maintenance: Use new logo for AppInfo

### CODE REVIEW

**Comment by wutschel** [comment]
Rebased to master.

**Comment by kambala-decapitator** [comment]
looks good.

Does it still work fine on iOS < 13?

**Comment by wutschel** [comment]
> Does it still work fine on iOS < 13?

Just checked on iPhone 6s iOS 11.4 simulator: Yes, it works.

**Review by kambala-decapitator — APPROVED** [review]

**Comment by wutschel** [comment]
Rebased to master.

**Pull request merged**
