### PR TITLE
Release Notes for 1.8

### PR DESCRIPTION
**Pull request by wutschel**
## Description

Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/357.

## Summary for release notes

[not app]

### CODE REVIEW

**Review by kambala-decapitator — APPROVED** [review]

**Comment by kambala-decapitator** [comment]
I'll keep this open in case you'd want to add more

**Comment by wutschel** [comment]
Updated the description.

**Comment by kambala-decapitator** [comment]
could you also update repo's readme the same way as description?

**Comment by wutschel** [comment]
> could you also update repo's readme the same way as description?

No problem, just did this.

**Comment by kambala-decapitator** [comment]
I guess nothing else to be added?

**Comment by wutschel** [comment]
No, this is good to go.

**Pull request merged**
