### PR TITLE
Update AppIcon

### PR DESCRIPTION
**Pull request by wutschel**
## Description

New App icon.

Screenshots:
https://abload.de/img/icon-1024guk54.png
https://abload.de/img/simulatorscreenshot-imoj58.png

## Summary for release notes

Maintenance: New App icon

### CODE REVIEW

**Comment by wutschel** [comment]
Rebased to master.

**Comment by kambala-decapitator** [comment]
not sure why this is draft :)

you used something like https://makeappicon.com/, didn't you?

**Comment by wutschel** [comment]
> not sure why this is draft :)

Because it is the icing on the cake of updated icons (https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/311 and https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/312) and I wanted to have final confirmation the App Icon is accepted. E.g. we can still go for a one with gray background which is more similar to the current color scheme.

> you used something like https://makeappicon.com/, didn't you?

It is the app "App Icon Maker Pro" from AppStore. If you have a better tool for this -- I am sure you have -- please let me know.

**Comment by kambala-decapitator** [comment]
I always use the website I linked, I believe your app does something similar. Icon resizer can be easily scripted anyway :)

**Review by kambala-decapitator — APPROVED** [review]

**Comment by wutschel** [comment]
Rebased to master.

**Pull request merged**
