### PR TITLE
Maintenance: Rework handling UTC dates

### PR DESCRIPTION
**Pull request by wutschel**
## Description

Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/443.

Use direct formatting via `[NSTimeZone timeZoneWithName:@"UTC"]` instead of indirect definition based on string formatting.

## Summary for release notes

Maintenance: Rework handling UTC dates

### CODE REVIEW

**Comment by wutschel** [comment]
@kambala-decapitator, marking as draft as I am still testing several use cases. But would be good if you could take a look at the solution I went for.

**Review by kambala-decapitator — APPROVED** [review]
Seems good!

Maybe already rename "XBMC PVR" to Kodi since you're touching those lines anyway?

**Comment by wutschel** [comment]
> XBMC PVR

Yep, did this and directly squashed it.

**Comment by kambala-decapitator** [comment]
Sorry, forgot to mention one more thing: in your message to the second commit there's a typo :)

**Comment by wutschel** [comment]
> Sorry, forgot to mention one more thing: in your message to the second commit there's a typo :)

You have eagle eyes. Fixed and rebased.

**Pull request merged**
