### PR TITLE
Replace magic numbers with enum for property "family"

### PR DESCRIPTION
**Pull request by wutschel**
## Description

Use enum instead of magic number for "family" property.

## Summary for release notes

Maintenance: Use enum instead of magic number for "family" property

### CODE REVIEW

**Review by kambala-decapitator — CHANGES_REQUESTED** [review]
overall fine, just 2 points:

1. drop `ft` prefix or replace with `Family`
2. use `switch` when checking the value

**Comment by wutschel** [comment]
I found it reasonable to use switch-case only at 1 place. The other location are not really making use of if-else a lot.

**Review by kambala-decapitator — APPROVED** [review]
perfect, thanks!

FYI you're doing the fixup not quite the intended way (git won't be able to squash commits automatically), please read about `--fixup` param to `git commit`. You can still squash manually with interactive rebase, of course.

**Comment by wutschel** [comment]
> please read about `--fixup` param to `git commit`.

Thanks, will do.

Last forced push just squashed the changes. If this is merged, I am not expecting to submit anything else today -- except in case of emergency. Let´s go for a build. :)

**Pull request merged**
