### PR TITLE
Translations update from Kodi Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Kodi Weblate](https://kodi.weblate.cloud) for [Kodi remotes/Official iOS Remote (main)](https://kodi.weblate.cloud/projects/kodi-remotes/official-ios-remote-main/).

It also includes following components:

* [Kodi remotes/Official iOS Remote (settings)](https://kodi.weblate.cloud/projects/kodi-remotes/official-ios-remote-settings/)

* [Kodi remotes/Official iOS Remote (InfoPlist)](https://kodi.weblate.cloud/projects/kodi-remotes/official-ios-remote-infoplist/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Review by gade01 — APPROVED** [review]

**Comment by wutschel** [comment]
@gade01, can you by chance also approve and push the two new German translation proposals i added in weblate for the new strings? As suggested I am following this flow now.

**Comment by gade01** [comment]
@wutschel 
German language is coordinated and maintainer by @ksooo 

I'd love to help, but this is not up to me.

**Comment by wutschel** [comment]
Thanks, will show patience then. :)

**Comment by ksooo** [comment]
Done. Both strings are now approved.

**Comment by gade01** [comment]
@ksooo Thanks a lot. 

@wutschel The changes should be pushed to this PR.

**Review by gade01 — APPROVED** [review]

**Pull request merged**
