### PR TITLE
Rework: Sort / section behaviour

### PR DESCRIPTION
**Pull request by wutschel**
## Description

This PR applies some rework to the visibility of sections/index in combination with sort mode. In general it is desired to only show sections/index if: 
a) The list has more than 100 entries
b) The user applied a different sort (method or order) than default

The code changes fix rule b) for Music Artists which was broken due to a missing configuration. In addition, this PR refactors building of sections to avoid code duplication and allows section/index for few more submenus which tend to have >100 list items.

Screenshots:
https://abload.de/img/bildschirmfoto2022-01ozkcn.png (remove unwanted sections)
https://abload.de/img/bildschirmfoto2022-018djcz.png (section/index for submenus if >100 list items)

## Summary for release notes

Bugfix: Align visibility of sections in artists list with other lists
Bugfix: Do not show dummy "/" section (e.g. >100 recently added songs)
Improvement: Allow section/index for Music/Movies/Videos/TVShow submenus

### CODE REVIEW

**Comment by kambala-decapitator** [comment]
should I check it already?

**Comment by wutschel** [comment]
> should I check it already?

Yes, please.

**Review by kambala-decapitator — COMMENTED** [review]
overall looks good.

The only thing I didn't understand is d3dcd71fa1de077e0bbafcd81f10e78f65be56dc. Could you explain its changes?

**Comment by wutschel** [comment]
> The only thing I didn't understand is [d3dcd71](https://github.com/xbmc/Official-Kodi-Remote-iOS/commit/d3dcd71fa1de077e0bbafcd81f10e78f65be56dc). Could you explain its changes?

Sure. The block I removed from `indexAndDisplayData` is already implemented the same way in `getIndexTableKey`. And `getIndexTableKey` is called in 'indexAndDisplayData' as well. I just needed to adapt the condition. Shall I update the commit's comment to make this easier to follow?

**Comment by kambala-decapitator** [comment]
> Shall I update the commit's comment to make this easier to follow?

yes please. I thought that either commit message is inaccurate or you accidentally included extra changes in the commit.

**Pull request merged**
