### PR TITLE
Translations update from Kodi Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Kodi Weblate](https://kodi.weblate.cloud) for [Kodi remotes/Official iOS Remote (main)](https://kodi.weblate.cloud/projects/kodi-remotes/official-ios-remote-main/).

It also includes following components:

* [Kodi remotes/Official iOS Remote (settings)](https://kodi.weblate.cloud/projects/kodi-remotes/official-ios-remote-settings/)

* [Kodi remotes/Official iOS Remote (InfoPlist)](https://kodi.weblate.cloud/projects/kodi-remotes/official-ios-remote-infoplist/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by wutschel** [comment]
@gade01, respect!. Quite some changes coming in now.

Two things I would like to ask:
1. Could the commit message just be reduced to "Translated using Weblate"? It now only shows the first translated language (Arabic), but 38 languages were updated.
2. Does it make sense to update the copyright header (sorry, I had overseen this in the first commit).

Copyright header could look like this:
```
/* 
  Localisable.strings
  XBMC Remote

  Created by Weblate yy/mm/dd.
  Copyright (c) 2022 Team Kodi. All rights reserved.
 */
```

Otherwise the update looks perfectly fine for me.

**Comment by gade01** [comment]
@wutschel Thanks, and this was translated using only Weblate translation memory. :)

I have changed and reduced the commit template to:
```
Translated using Weblate

{{ language_name }}
Currently translated at {{ stats.translated_percent }}% ({{ stats.translated }} of {{ stats.all }} strings)

Translation: {{ project_name }}/{{ component_name }}
```

Weblate is having a hard time cleaning the commit message up for this PR, but at least the commit name is now only "Translated using Weblate".
For the next PR everything should look correct.

>Does it make sense to update the copyright header

That's totally up to you.
It will have to be done with a bulk edit for language files, as Weblate can't change this once languages are created.
We just have to make sure that no uncommitted changes are at Weblate repo before doing the copyright changes.

**Comment by kambala-decapitator** [comment]
@wutschel so, good to merge?

**Comment by wutschel** [comment]
> @wutschel so, good to merge?

Yup.

**Pull request merged**
