### PR TITLE
Translations update from Kodi Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Kodi Weblate](https://kodi.weblate.cloud) for [Kodi remotes/Official iOS Remote (main)](https://kodi.weblate.cloud/projects/kodi-remotes/official-ios-remote-main/).

It also includes following components:

* [Kodi remotes/Official iOS Remote (settings)](https://kodi.weblate.cloud/projects/kodi-remotes/official-ios-remote-settings/)

* [Kodi remotes/Official iOS Remote (InfoPlist)](https://kodi.weblate.cloud/projects/kodi-remotes/official-ios-remote-infoplist/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by wutschel** [comment]
The German change is not ok. Not sure why it was approved in Weblate.

**Comment by kambala-decapitator** [comment]
iiuc this can't be merged until German translation is fixed and the update is pushed here?

**Comment by wutschel** [comment]
Yep, sadly. I already proposed the change in Weblate. Currently this is translated not well and on top is inconsistent between singular and plural.

**Comment by kambala-decapitator** [comment]
@gade01 do I understand correctly that for the German fix to appear, this PR must be merged first?

**Comment by wutschel** [comment]
It needs ro be approved first. Currently the proposal is still open, I have no right to accept it.

**Comment by kambala-decapitator** [comment]
seems I can't either

**Comment by gade01** [comment]
@wutschel 
That's very correct. Weblate PR's should always be merged first to avoid merge conflicts at Weblate.

**Review by gade01 — APPROVED** [review]

**Comment by wutschel** [comment]
@gade01, even if the fix is going through Weblate as well (I am not aiming to apply the fix via GitHub)? I thought, if there is an open PR like this one, and more changes are approved in Weblate, this PR would be updated. Wasn't this what we were seeing during the past two weeks?

**Comment by gade01** [comment]
@wutschel 
Maybe I misunderstood your question, sorry :)
Yeah, Weblate will push to the same open PR until it is merged.

But if strings in en_gb should be changed, an open Weblate PR or uncommitted changes at Weblate must always be merged first.

**Comment by wutschel** [comment]
@gade01, do you by chance have the rights to approve the fix in the German translation and push it? This currently blocks this PR.

**Comment by gade01** [comment]
Absolutely.
I just approved the suggestion and pushed it.

**Comment by wutschel** [comment]
gade01, great, thanks!

@kambala-decapitator, ready to go :)

**Comment by gade01** [comment]
@wutschel 
@ksooo told me that this exact string was changed purposely because of inconsistency with the same string in the German translations.

I very much try to achieve consistency in the Danish translations myself.

He wrote:
> ...either the English source string should be changed to "Ratings“ and German to „Bewertungen“ or translation should stay as it is now, like it was before the change. „Votes“ translates to „Stimmen“

**Comment by wutschel** [comment]
@gade01, @ksooo, let us just ensure we are consistent. There are two strings which need to be aligned: vote/votes should translate to Stimme/Stimmen, if we want to make this change. The last PR was only updating one of them.

**Comment by ksooo** [comment]
> vote/votes should translate to Stimme/Stimmen, if we want to make this change.

Should be consistent now on Weblate: vote -> Stimme, votes -> Stimmen

**Pull request merged**
