### PR TITLE
Improvement: Sort settings array before displaying

### PR DESCRIPTION
**Pull request by wutschel**
## Description

partially solves https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/981.

Sort the array of values before displaying it in the settings UI.

## Summary for release notes

Improvement: Sort settings array before displaying

### CODE REVIEW

**Comment by kambala-decapitator** [comment]
but it still won't show setting names, only indexes, will it?

**Comment by wutschel** [comment]
Yep. Was never looking into this yet. API response provides labels which could be used (same as are shown in the UI list). I guess it was done this way to limit the characters to be displayed. Same happens for the skip steps. It shows "-600, -300, ...", but the API also provides "-10 min" and "-5 min". But then the whole list would exceed the available space.

**Comment by kambala-decapitator** [comment]
ok, will merge this, but will keep the issue open

> But then the whole list would exceed the available space.

options text can be comma-separated in a multiline label

**Comment by wutschel** [comment]
> ok, will merge this, but will keep the issue open
> 
> > But then the whole list would exceed the available space.
> 
> options text can be comma-separated in a multiline label

Sounds good. I will add some comments in the issue to state what is left open.

**Pull request merged**
