### PR TITLE
[german] fix typo 'Unterstitel -> Untertitel'

### PR DESCRIPTION
**Pull request by howie-f**
follow up to https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/119 german translations
just caught my eye recently

### CODE REVIEW

**Comment by wutschel** [comment]
What do you think about rewording the translation for "button" from "Schalter" to "Taste"? For me a "Schalter" is more like a switch. "Taste" would be imho be a better match for "button".

**Comment by howie-f** [comment]
agree `Taste` would be better, as `Schalter` is definitely a switch.
grep -R 'Schalter' gave me 8 hits. i think it's fine to change, if @BBJake has no objections i could change it by the weekend.
or somebody of you wants to take on it.. just let me know

**Comment by howie-f** [comment]
hrm, my gui is mixed english / german. i would change the `button` translation anyways, but there seems to be a problem somewhere else... :)

IMG_0064

**Comment by wutschel** [comment]
This does not look like software from latest master. Are your sure this is your local build?

**Comment by BBJake** [comment]
> agree `Taste` would be better, as `Schalter` is definitely a switch.
> grep -R 'Schalter' gave me 8 hits. i think it's fine to change, if @BBJake has no objections i could change it by the weekend.
> or somebody of you wants to take on it.. just let me know

I can change this...

**Comment by wutschel** [comment]
As you are on it:

1. "Are you sure you want to suspend your XBMC system now?" = "Bist du sicher, dass **Du** dein Kodi-System jetzt in den **Stanyby** gehen soll?"; -> should be "Bist du sicher, dass dein Kodi-System jetzt in den Standby gehen soll?";
2. "Are you sure you want to hibernate your XBMC system now?" = "Bist du sicher, dass **Du** dein Kodi-System jetzt in den Ruhezustand gehen soll?"; -> "Bist du sicher, dass dein Kodi-System jetzt in den Ruhezustand gehen soll?"; 
3. "Are you sure you want to quit XBMC application now?" = "Bist du sicher, dass Du **die** Kodi jetzt beenden möchtest?"; -> "Bist du sicher, dass Du Kodi jetzt beenden möchtest?";
4. "Scrubbing 0.05" = "Scrubbin**g.G**eschwindigkeit: Sehr fein"; ->  "Scrubbin**g-G**eschwindigkeit: Sehr fein";
5. "Scrubbing 0.025" = "Scrubbin**g.G**eschwindigkeit: Super fein"; -> "Scrubbin**g-G**eschwindigkeit: Super fein";
6. We should either always use "**add-on**" also for German or go for "**Erweiterung**". Currently this is mixed. I am favoring "add-on".

**Comment by howie-f** [comment]
> This does not look like software from latest master. Are you sure this is your local build?

no, sure this is the version from the app store. please ignore my comment

> I can change this...

thanks @BBJake

**Comment by BBJake** [comment]
I was also not satisfied with "Schalter", so on my system I already changed to this
image

I think at this part an action ist defined, so maybe "Aktion" is better describing the function here...

**Comment by wutschel** [comment]
Well, I think "Funktionen..." was quite ok, maybe even "Einstellungen..." or simply "Mehr ..." (which I still prefer). When entering this, you are able to read and set a huge variety of Kodi internal settings.

**Comment by BBJake** [comment]
> As you are on it:
> 
> 1. "Are you sure you want to suspend your XBMC system now?" = "Bist du sicher, dass **Du** dein Kodi-System jetzt in den **Stanyby** gehen soll?"; -> should be "Bist du sicher, dass dein Kodi-System jetzt in den Standby gehen soll?";
> 2. "Are you sure you want to hibernate your XBMC system now?" = "Bist du sicher, dass **Du** dein Kodi-System jetzt in den Ruhezustand gehen soll?"; -> "Bist du sicher, dass dein Kodi-System jetzt in den Ruhezustand gehen soll?";
> 3. "Are you sure you want to quit XBMC application now?" = "Bist du sicher, dass Du **die** Kodi jetzt beenden möchtest?"; -> "Bist du sicher, dass Du Kodi jetzt beenden möchtest?";

Ok, fixed.

> 4. "Scrubbing 0.05" = "Scrubbin**g.G**eschwindigkeit: Sehr fein"; ->  "Scrubbin**g-G**eschwindigkeit: Sehr fein";
> 5. "Scrubbing 0.025" = "Scrubbin**g.G**eschwindigkeit: Super fein"; -> "Scrubbin**g-G**eschwindigkeit: Super fein";

Fixed.

> 6. We should either always use "**add-on**" also for German or go for "**Erweiterung**". Currently this is mixed. I am favoring "add-on".

I also was not sure what to prefer. But I will change all of this to "add-on"

**Comment by howie-f** [comment]
included in https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/129

**Pull request closed without merging**
