### PR TITLE
Translations update from Kodi Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Kodi Weblate](https://kodi.weblate.cloud) for [Kodi remotes/Official iOS Remote (main)](https://kodi.weblate.cloud/projects/kodi-remotes/official-ios-remote-main/).

It also includes following components:

* [Kodi remotes/Official iOS Remote (InfoPlist)](https://kodi.weblate.cloud/projects/kodi-remotes/official-ios-remote-infoplist/)

* [Kodi remotes/Official iOS Remote (settings)](https://kodi.weblate.cloud/projects/kodi-remotes/official-ios-remote-settings/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by wutschel** [comment]
What is this change about?

**Comment by kambala-decapitator** [comment]
@gade01 any idea what's going on?

**Comment by gade01** [comment]
@kambala-decapitator @wutschel 
Weblate has created some major problems.
A lot of languages were auto created and this messed up a lot of stuff.
I'm in the process of fixing this, but it will take days.
Please leave this PR open. I Will ping you when everything is ready. 
Thanks

**Comment by kambala-decapitator** [comment]
> @kambala-decapitator @wutschel 
> 
> Weblate has created some major problems.
> 
> A lot of languages were auto created and this messed up a lot of stuff.
> 
> I'm in the process of fixing this, but it will take days.
> 
> Please leave this PR open. I Will ping you when everything is ready. 
> 
> Thanks

Thanks!

Can we merge other PRs?

**Comment by wutschel** [comment]
> Can we merge other PRs?

Valid question. There is one PR which changes the localization / translation.

**Comment by gade01** [comment]
@kambala-decapitator @wutschel 
Weblate has created some major problems.
A lot of languages were auto created and this messed up a lot of stuff.
I'm in the process of fixing this, but it will take days.
Please leave this PR open. I Will ping you when everything is ready. 
Thanks

> > Can we merge other PRs?
> 
> Valid question. There is one PR which changes the localization / translation.

You can merge PR's that don't touch language files at all.
Otherwise we will have merge conflicts at Weblate and my work to fix the errors will be lost. 

Language changes should always be done at Weblate and not by PR's.

**Comment by wutschel** [comment]
> Language changes should always be done at Weblate and not by PR's.

That's clear. The PR only changes the reference (English). But even this PR we should not merge now, understood. We will wait until you're giving green light for this.

**Comment by gade01** [comment]
> > Language changes should always be done at Weblate and not by PR's.
> 
> That's clear. The PR only changes the reference (English). But even this PR we should not merge now, understood. We will wait until you're giving green light for this.

Exactly, sounds great.
You're correct that the source file (English) should be changed by PR. Weblate will sync all other languages from this file.

Thanks guys ;)

**Comment by gade01** [comment]
@wutschel @kambala-decapitator 
I can't remember if strings can be empty if not translated, eg.
https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/932/files#diff-0e98f6ca4e9465748d3a3f4dddc8ae4df2a115d52cad13fd8b0bdec705574959R5
Or do they need to be filled with the source language?
Will empty strings fallback to the source file if not translated, like other Kodi addons?

**Comment by wutschel** [comment]
> Or do they need to be filled with the source language?
> Will empty strings fallback to the source file if not translated, like other Kodi addons?
Just tested this. The strings must not be empty. If not translated yet, they must be either not listed in the language file, or they must just use the default English text.

**Comment by gade01** [comment]
Ok I see.
Would it be good practice to completely remove empty strings from the language files?

**Comment by wutschel** [comment]
> Maybe it's best to keep translation files clean and remove untranslated strings?

I think so as well. Translations are anyway done via Weblate, so it is ok to not show all possible (and not yet translated) strings.

**Comment by wutschel** [comment]
Looks a lot better. I see only 3 places left where `= ""` is added.

**Comment by gade01** [comment]
> Looks a lot better. I see only 3 places left where `= ""` is added.

Yeah, everything moved forward. 
But this is really a struggle and right now I'm restoring lost Spanish (Mexico) translations.

The good thing is that this will leave translations in a far better shape than before.

**Comment by wutschel** [comment]
Again looks better now. The added `= ""` are gone. But now I see some changes which end up with `NSLocalNetworkUsageDescription=` statements without any assigned string.

**Comment by gade01** [comment]
> Again looks better now. The added `= ""` are gone. But now I see some changes which end up with `NSLocalNetworkUsageDescription=` statements without any assigned string.

Very well spotted.
I changed some addons at Weblate, and it should be fixed now.

I'm still restoring lost translations ;)

**Comment by wutschel** [comment]
> Very well spotted. I changed some addons at Weblate, and it should be fixed now.

Yes, this is fixed now.

> I'm still restoring lost translations ;)

Ok, let us know when this is good enough to get merged and we can also add one of the open MRs which will update the reference English translation files.

**Comment by wutschel** [comment]
@gade01, you see some light at the end of the tunnel?

**Comment by wutschel** [comment]
> Thanks for the patience guys. I think everything looks even better now than before.
> 
> Please let me know if I missed anything.

Thanks for the latest updates. Seems you renamed some files (Portuguese only. Not sure, if this will break the build) and the Portuguese translation for the network access notification is lost. If this is clarified, I think we can go ahead.

But in general I am not sure about the rules which either remove or keep the non-translated strings in the language files. In some language files these are removed, in some files they are partially removed and in some they just reside. It doesn't change the overall result for the App, I am just wondering.

**Comment by gade01** [comment]
> > Thanks for the patience guys. I think everything looks even better now than before.
> > Please let me know if I missed anything.
> 
> Thanks for the latest updates. Seems you renamed some files (Portuguese only. Not sure, if this will break the build) and the Portuguese translation for the network access notification is lost. If this is clarified, I think we can go ahead.
> 
> But in general I am not sure about the rules which either remove or keep the non-translated strings in the language files. In some language files these are removed, in some files they are partially removed and in some they just reside. It doesn't change the overall result for the App, I am just wondering.

All files should be lower case.
So I changed files, which were named incorrectly.
Eg. pt-PT to pt-pt

That shouldn't be a problem as all other files are lower case.

I can change Weblate to use whatever rule you like.
Either to keep empty strings, to remove empty strings or to fill empty strings with the en_gb source strings.
I think Weblate will update the files regularly, but not all at once.

**Comment by wutschel** [comment]
> All files should be lower case. So I changed files, which were named incorrectly. Eg. pt-PT to pt-pt

Ok, then I will need to see, if I need to apply further changes to the project to deal with it. But can you then please restore the translation of the Portuguese InfoPlist.strings to finalize this PR? This got lost when moving to lower case naming.

> I can change Weblate to use whatever rule you like. Either to keep empty strings, to remove empty strings or to fill empty strings with the en_gb source strings. I think Weblate will update the files regularly, but not all at once.

Understood, but I am not sure, if the same that I was referring to: In some cases e.g. `"Automatic" = "Automatic";` is removed (as not translated), and in other cases it is kept. And this is the same for other words as well.

**Comment by kambala-decapitator** [comment]
@gade01 could you help us solving the last point outlined by @wutschel above?

**Comment by wutschel** [comment]
Still same problem.

**Comment by gade01** [comment]
@wutschel @kambala-decapitator 
Sorry it's been some time. I'm extremely busy at the moment.

I think I fixed the pt-pt translations.
I used my phone, so please check that everything looks correct.

**Comment by wutschel** [comment]
Thanks, @gade01. Appreciate you fixed this.

The missing PT string is back. I did not check all other changes again as I did this already too often and the amount of changes is quite huge. Let's go for it and move on.

**Comment by gade01** [comment]
> Thanks, @gade01. Appreciate you fixed this.
> 
> The missing PT string is back. I did not check all other changes again as I did this already too often and the amount of changes is quite huge. Let's go for it and move on.

Yeah, I agree.
We can always fix things further in a new PR if needed.

**Pull request merged**
