### PR TITLE
Release Notes 1.10

### PR DESCRIPTION
**Pull request by wutschel**
## Description

Updating Release Notes for App version 1.10

## Summary for release notes

[not app] Updating Release Notes for App version 1.10

### CODE REVIEW

**Comment by kambala-decapitator** [comment]
I think it'd be good to add the MAC address fix #635

**Comment by wutschel** [comment]
> I think it'd be good to add the MAC address fix #635

For sure, was just waiting for it to be merged.

**Comment by kambala-decapitator** [comment]
#638 new languages to be added

**Comment by wutschel** [comment]
Added the new languages to the "features" section -- quite long release notes this time. :)

**Comment by heitbaum** [comment]
@wutschel / @kambala-decapitator - tested 3288 on both:
- iPad Pro (9.7-inch) 15.3.1
- iPhone 12 Pro 15.4

all the stuff I use looks good.

**Comment by kambala-decapitator** [comment]
@wutschel can be merged?

**Comment by wutschel** [comment]
> @wutschel can be merged?

Yes. No more feature or fix to be added so far. Let's go.

**Pull request merged**
