### PR TITLE
Bugfix: Fix writing of "Now Playing" in main menu

### PR DESCRIPTION
**Pull request by wutschel**
## Description

Use "Now Playing" instead of "Now playing".

## Summary for release notes

Bugfix: Fix writing of "Now Playing" in main menu for en and en-US

### CODE REVIEW

**Comment by kambala-decapitator** [comment]
shouldn't such things be fixed in Weblate?

**Comment by wutschel** [comment]
> shouldn't such things be fixed in Weblate?

Seems I could do for en_US, but cannot for en_GB (maybe because it the reference?).

@gade01, can you help out with this? Just want to change "Now playing" to "Now Playing" for en_GB and en_US.

**Comment by gade01** [comment]
@kambala-decapitator @wutschel 
Yeah, all changes at language files other than en_gb should be done at Weblate.
en_gb should be changed directly ay Github. Just make sure there are no uncommitted changes at Weblate before doing this.

I can change en_us, en_au and en_nz: https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/631

**Comment by kambala-decapitator** [comment]
@gade01 thanks for the clarification!

@wutschel please remove the change for en-US.

**Comment by wutschel** [comment]
@gade01, thanks for explaining this.

@kambala-decapitator, done.

**Pull request merged**
