### PR TITLE
[german] fix typo: 'Aufnehemen'

### PR DESCRIPTION
**Pull request by howie-f**
## Description
German translation for `Record` is `Aufnehmen`

@wutschel

EDIT: or should things like this be handled in Weblate? idk

### CODE REVIEW

**Comment by wutschel** [comment]
Thanks for pointing this out. I proposed this change in Weblate. As I am also still new to Weblate I am not sure by when this will be reviewed and by when the PR would show up though.

@kambala-decapitator, this should also be merged before releasing 1.9.

**Comment by howie-f** [comment]
👍 thanks wutschel

**Comment by wutschel** [comment]
I found one more: "Im Party-Modus wiedergaben" should be "Im Party-Modus wiedergeben"

**Comment by howie-f** [comment]
ok, perhaps @ksooo as german reviewer can tell us if the proposed changes will be merged in time

**Comment by ksooo** [comment]
Proposed changes committed and pushed to GitHub.

**Comment by howie-f** [comment]
cool, thank you

**Pull request closed without merging**
