### PR TITLE
Translations update from Kodi Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Kodi Weblate](https://kodi.weblate.cloud) for [Kodi remotes/Official iOS Remote (main)](https://kodi.weblate.cloud/projects/kodi-remotes/official-ios-remote-main/).

It also includes following components:

* [Kodi remotes/Official iOS Remote (InfoPlist)](https://kodi.weblate.cloud/projects/kodi-remotes/official-ios-remote-infoplist/)

* [Kodi remotes/Official iOS Remote (settings)](https://kodi.weblate.cloud/projects/kodi-remotes/official-ios-remote-settings/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by icarok99** [comment]
Leave to merge when translation is complete.

**Comment by wutschel** [comment]
@icarok99, we will merge the translation changes as they come in. The App will start adding the new language/translation when we translation states reached >70%.

**Comment by icarok99** [comment]
<a href="https://kodi.weblate.cloud/engage/kodi-remotes/-/pt_br/">
Status da tradução
</a>

**Comment by wutschel** [comment]
> [ Status da tradução ](https://kodi.weblate.cloud/engage/kodi-remotes/-/pt_br/)

@icarok99 , PT-BR was enabled with https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/1167 and will be part of next TestFlight build.

**Pull request merged**
