### PR TITLE
Translations update from Kodi Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Kodi Weblate](https://kodi.weblate.cloud/projects/kodi-misc/official-ios-remote-main/)
for Kodi misc/Official iOS Remote (main).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by kambala-decapitator** [comment]
@gade01 any idea why such an important change was added?

**Comment by gade01** [comment]
@kambala-decapitator LOL.
I have no idea.
I'm adding the language at Weblate right now.

**Comment by gade01** [comment]
And this doesn't seem right:
https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/502/files#diff-3c65018273fad76bdea2490f0de432f2478094d7f2272ada26725023871e6634R3

Better wait with merging.
I'll look at everything tomorrow morning.

**Comment by wutschel** [comment]
The German translation has the expected fixes. Looks good.

**Review by gade01 — APPROVED** [review]
>And this doesn't seem right:
https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/502/files#diff-3c65018273fad76bdea2490f0de432f2478094d7f2272ada26725023871e6634R3

I can see all other translations are formatted the same way.

The two extra lines won't anything.
Everything looks good to me.

**Pull request merged**
