### PR TITLE
Translations update from Kodi Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Kodi Weblate](https://kodi.weblate.cloud) for [Kodi remotes/Official iOS Remote (main)](https://kodi.weblate.cloud/projects/kodi-remotes/official-ios-remote-main/).

It also includes following components:

* [Kodi remotes/Official iOS Remote (settings)](https://kodi.weblate.cloud/projects/kodi-remotes/official-ios-remote-settings/)

* [Kodi remotes/Official iOS Remote (InfoPlist)](https://kodi.weblate.cloud/projects/kodi-remotes/official-ios-remote-infoplist/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by wutschel** [comment]
The German change in the translation is not desired and wrong. I already proposed in Weblate to change this back.

**Review by gade01 — APPROVED** [review]

**Comment by gade01** [comment]
@wutschel 
> The German change in the translation is not desired and wrong. I already proposed in Weblate to change this back.

I accepted your change at Weblate.
The problem is that the English string has a trailing whitespace: `Pictures `.
This leads Weblate to automatically add a whitespace after the translation.

**Comment by kambala-decapitator** [comment]
@wutschel so, ok to merge?

**Comment by wutschel** [comment]
> @wutschel so, ok to merge?

Not yet, the German change would cause an issue.

**Comment by wutschel** [comment]
> I accepted your change at Weblate. The problem is that the English string has a trailing whitespace: `Pictures `. This leads Weblate to automatically add a whitespace after the translation.

@gade01, just checked in Weblate again. Looks like to trailing space is back again?

**Comment by gade01** [comment]
@wutschel 
As I wrote above, the source English string contains a trailing space: `Pictures `
That's why Weblate is automatically inserting the trailing space to match it to the source file.

As long as the source string contains a trailing space, Weblate will behave this way.

**Comment by wutschel** [comment]
There are more strings like this and these translations are not forced to have trailing spaces.

**Comment by gade01** [comment]
The ones made at Weblate have the trailing spaces: 
https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/559/files#diff-0abe11e877fc17e6f2d40f255f49979f5dc64302aaa3027e44b6283b17b0f037R305

https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/559/files#diff-690ee01f4f3c6003bd0ebe9fcf2a40697f63f78551ccd76f8fdb86ef99d7cf9bR303

May I ask why the German translation should vary from the English source string?

**Comment by wutschel** [comment]
> May I ask why the German translation should vary from the English source string?

Sure. The strings of interest are used when building a sentence from two parts: "Are you sure you want to clear the %@playlist?", whereas %@ is one of the strings with the trailing spaces (e.g. "Pictures " or "Video "). In German in such case "-" instead of a trailing space is used to combine the parts. Maybe it is simpler to just use three different strings holding the complete sentence, and to translate them.

But why is the same not happening for the other two strings ("Video " and "Music ") which also do not have a trailing space for the German translation?

**Comment by gade01** [comment]
Ah, I see. That makes sense. :)

>But why is the same not happening for the other two strings ("Video " and "Music ") which also do not have a trailing space for the German translation?

I'm not exactly sure why Weblate did not change the other two strings.
For `Bilder-` I think the trailing space was added (maybe by Weblate) when the string was approved by @ksooo but I'm not sure.

https://kodi.weblate.cloud/translate/kodi-remotes/official-ios-remote-main/de_de/?q=pictures&sort_by=-priority%2Cposition&offset=3#history

Now it's apparently difficult to remove again.

**Comment by kambala-decapitator** [comment]
> Are you sure you want to clear the %@playlist?

I think the best would be moving the `playlist` word into translations. Other languages might require special translation of "X playlist" as well.

**Comment by gade01** [comment]
I totally agree.
Eg. in Danish it translated differently. 
I would move the entire strings to the translations:

`Are you sure you want to clear the video playlist?`

`Are you sure you want to clear the music playlist?`

Etc.

**Comment by wutschel** [comment]
Let's merge this one. I will provide a PR to introduce three complete sentences -- one for each playlist type. I can use the current localized strings as starting point.

**Comment by gade01** [comment]
Sounds like a great plan.

**Comment by wutschel** [comment]
> Sounds like a great plan.

Done. As far as I can see this also helps with other languages. Most likely the context was lost during the translation, and now this becomes clear: e.g. "playlist de música" instead of "Música playlist".

**Pull request merged**
