### PR TITLE
Improvement: Remove confirmation of power menu actions

### PR DESCRIPTION
**Pull request by wutschel**
## Description

Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/1116.

This PR removes the need confirm power menu actions which include updating/cleaning libraries, leaving Kodi application,  shutting down or hibernating the Kodi system. It also lets Wake-on-LAN only show success (when the command could be issued) or failure (when in need of MAC address).

## Summary for release notes

Improvement: Remove confirmation of power menu actions

### CODE REVIEW

**Comment by wutschel** [comment]
To make this easier to revert (just in case of strong feedback), I would remove the change to the English language file. This can be done at a later point in time and avoids trouble with the translation being removed and requiring translation in case we revert back.

**Comment by kambala-decapitator** [comment]
> To make this easier to revert (just in case of strong feedback), I would remove the change to the English language file. This can be done at a later point in time and avoids trouble with the translation being removed and requiring translation in case we revert back.

I agree, very good idea

**Comment by wutschel** [comment]
Oh, now you merged this with all the first-remove-then-revert commits -- which I wanted to remove once you reviewed the MR. I hope this does not cause trouble with weblate.

**Comment by kambala-decapitator** [comment]
> Oh, now you merged this with all the first-remove-then-revert commits -- which I wanted to remove once you reviewed the MR. I hope this does not cause trouble with weblate.

shouldn't be a problem as weblate should look only at merge commit which doesn't have any localization changes

**Pull request merged**
