### PR TITLE
Improvement: Global Search support for cast, plot and tagline

### PR DESCRIPTION
**Pull request by wutschel**
## Description

This PR implements support to search for `cast`, `plot` and `tagline` in Global Search. For `cast` both actors and roles can be searched.
- `cast` is supported for Movies and TV Shows,
- `plot` is supported for Movies and Videos
- `tagline` is supported for Movies

## Summary for release notes

Improvement: Global Search support for cast, plot and tagline

### CODE REVIEW

**Comment by wutschel** [comment]
This now caused an undesired regression (major increase of sync time). With my small test database I was recognizing this. Can the PR still be reverted? Or do I need to create a new PR for this?

**Comment by wutschel** [comment]
> This now caused an undesired regression (major increase of sync time). With my small test database I was recognizing this. Can the PR still be reverted? Or do I need to create a new PR for this?

Edit: There is small improvement in there which I would to not revert it was removing an unused variable in DetailViewController. So maybe better to just create a new PR rolling back the changes and add statement on the resolved regression in the "Summary for release notes" section?

**Comment by kambala-decapitator** [comment]
I can revert the whole PR and then create another one by cherry-picking the small improvement commit

**Comment by wutschel** [comment]
> I can revert the whole PR and then create another one by cherry-picking the small improvement commit

Great, let's do.

**Pull request merged**
