### PR TITLE
Avoid potential crashes

### PR DESCRIPTION
**Pull request by wutschel**
## Description

Fixes crashes reported in https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/323.

## Summary for release notes

Bugfix: Avoid potential crashes

### CODE REVIEW

**Comment by wutschel** [comment]
Rebased to master.

**Comment by wutschel** [comment]
Rebased to master.

**Review by kambala-decapitator — APPROVED** [review]
looks good!

Have you managed to reproduce the crashes? For example, which unexpected type arrives in `duration`?

**Comment by wutschel** [comment]
> Have you managed to reproduce the crashes? For example, which unexpected type arrives in `duration`?

I couldn´t reproduce which use case this comes from. But I was forcing such crash when calling `duration` with an unexpected type. The crash log looks same as in the shared ones.

**Pull request merged**
