### PR TITLE
Feature: Major refresh and alignment of icons with Kodi 19

### PR DESCRIPTION
**Pull request by wutschel**
## Description

Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/310 (remote control is changed with a separate PR). The App uses quite aged icons. This PR refreshes the icons/buttons based on current Kodi 19. Screenshots can be found in https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/310.

## Summary for release notes

Feature: Refresh icons (aligned with Kodi 19)

### CODE REVIEW

**Comment by wutschel** [comment]
I am adding this PR as work-in-progress to allow testing. It should be added only after the bigger code style and AppDelegate rework PRs to avoid problems rebasing those.

**Comment by wutschel** [comment]
Rebased to master.

**Comment by wutschel** [comment]
Added few more icons, following the 1-color / 2-dimensional look.

**Comment by wutschel** [comment]
Rebased to master.

**Review by kambala-decapitator — APPROVED** [review]
I reviewed only code changes

**Pull request merged**
