### PR TITLE
Translations update from Kodi Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Kodi Weblate](https://kodi.weblate.cloud) for [Kodi remotes/Official iOS Remote (main)](https://kodi.weblate.cloud/projects/kodi-remotes/official-ios-remote-main/).

It also includes following components:

* [Kodi remotes/Official iOS Remote (settings)](https://kodi.weblate.cloud/projects/kodi-remotes/official-ios-remote-settings/)

* [Kodi remotes/Official iOS Remote (InfoPlist)](https://kodi.weblate.cloud/projects/kodi-remotes/official-ios-remote-infoplist/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by wutschel** [comment]
@gade01, was this desired?

**Comment by gade01** [comment]
@wutschel 
I had a nice talk with @kambala-decapitator about languages for remotes.
I have had some language requests bby translators for remotes already.

It could be nice to add all languages supported by Weblate.
If a language gets translated >50% we can add app support for that language.
If a language is untranslated, we just leave it until it gets further translated.

What do you think?

**Comment by gade01** [comment]
I'm currently creating all languages at Weblate.
It has some bug, so I have to create languages one by one.

**Comment by gade01** [comment]
@wutschel @kambala-decapitator 
All languages are added now.
What are your thoughts on this?

**Comment by wutschel** [comment]
@gade01, @kambala-decapitator, seeing this change I am personally not convinced. It adds 70-times (?) the same text files into different locations. I often search for strings and would have about 70*2 false positives (or even twice as much for some strings which are present in both the root and localized strings file) which will make it harder to find the one of interest. I will get used to this, but for now it seems like not being helpful. Is there really no other way to prepare web late for new translations? E.g. only submitting to project when a certain translation percentage was reached?

If it should be decided to get merged: Still the English (en) translations are the leading ones, right? So, any string which would be removed or added there will also be removed or added in all other files.

**Comment by kambala-decapitator** [comment]
@gade01 any chance to remove these strange "update translation files" commits and have properly named ones that mention language? Not strictly required, but would be good for a cleaner history.

@wutschel this PR only adds files to the repo, it's up to us to decide which ones to include in the project and at which point. If you search for strings within Xcode, then you aren't affected (but with grep you'll have to filter files).

> Still the English (en) translations are the leading ones, right? So, any string which would be removed or added there will also be removed or added in all other files.

to my understanding you're right. @gade01 could you confirm?

**Comment by gade01** [comment]
@wutschel It's totally up to you if we do this.
Translators definitely request the languages :)

I don't see any issue with doing this and searching for strings.
I already do the same for my own addons.
Languages are added like this for all addons, skins, core etc.
And languages need to exist in Weblate and Github before translators have access at Weblate and can translate them. 

English (en) will always be the source file for all languages.
So any changes to the English files are always synced with all languages.

**Comment by wutschel** [comment]
Ok, then let's go for it and cross fingers we get more translations by doing so. :)

**Comment by gade01** [comment]
@wutschel That sounds great.
I can see some strings are already translated.

**Comment by wutschel** [comment]
> Would it be a solution to squash all commits into one?

+1 from me.

**Comment by gade01** [comment]
That should be it.
Now there's only 1 commit :)

**Comment by kambala-decapitator** [comment]
thanks! LGTM.

**Comment by wutschel** [comment]
> @wutschel this PR only adds files to the repo, it's up to us to decide which ones to include in the project and at which point. If you search for strings within Xcode, then you aren't affected (but with grep you'll have to filter files).

Sadly this is not the case. If I search for e.g. "Automatic", I now get 157 results in 83 files. :/

**Comment by wutschel** [comment]
I will find a way.

**Pull request merged**
