### PR TITLE
add PR template

### PR DESCRIPTION
**Pull request by kambala-decapitator**
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

### CODE REVIEW

**Comment by kambala-decapitator** [comment]
@wutschel do you find this ok? Anything to add?

**Comment by wutschel** [comment]
> @wutschel do you find this ok? Anything to add?

The two sections should be ok. I would just rename the second section to something like `## Testflight description`, `## User readable summary` or `## Summary for release notes`

**Comment by wutschel** [comment]
I have a small fix and will wait with raising the PR until this is merged. We can start using the new template then.

**Comment by kambala-decapitator** [comment]
> Summary for release notes

I picked this one

**Pull request merged**
