### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Weblate](https://kodi.weblate.cloud/projects/kodi-misc/official-ios-remote-main/) for Kodi misc/Official iOS Remote (main).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by wutschel** [comment]
From my point of view the translations are making things worse. They bring in inconsistencies for the main menu config and the translation of channels.

**Comment by kambala-decapitator** [comment]
> From my point of view the translations are making things worse. They bring in inconsistencies for the main menu config and the translation of channels.

IMO such things should be discussed on Weblate, see for example https://kodi.weblate.cloud/translate/kodi-misc/official-ios-remote-settings/de_de/?checksum=b4b5d12d082e8d85&q=%22Show+RADIO%22&sort_by=-priority%2Cposition

**Comment by wutschel** [comment]
I proposed changes for the texts which would cause inconsistencies. Let's see ...

**Comment by kambala-decapitator** [comment]
if I read the "show radio" activity right, @ksooo rejected your suggestion.

@wutschel I think you need to register on weblate (that you're not anonymous and it's clear who's suggesting) and discuss the best approach there (or maybe in a GH issue).

**Comment by wutschel** [comment]
Reached out to @ksooo and proposed several changes in weblate based on the given feedback. With this we should reach consistency again.

**Comment by wutschel** [comment]
@ksooo, if I saw right you reviewed/updated the whole German translation. Thanks for that! When do you think the PR would be updated by weblate?

**Comment by ksooo** [comment]
> When do you think the PR would be updated by weblate?

 Happened just now.

**Comment by wutschel** [comment]
Great. Looks good to me.

**Pull request merged**
